defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            type: "posts"
        values:
            layout: "post"
repository: NilsIRL/Blindspot
